projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - ./*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-east-1
        apiId: null
        frontend: ios
        maxDepth: 4
